//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.20 at 10:50:19 ���� CST 
//


package com.deve.timeschedule.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.letv.taskplugin.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.letv.taskplugin.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jobs.Job.Params }
     * 
     */
    public Jobs.Job.Params createJobsJobParams() {
        return new Jobs.Job.Params();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link Jobs.Job.Trigger }
     * 
     */
    public Jobs.Job.Trigger createJobsJobTrigger() {
        return new Jobs.Job.Trigger();
    }

    /**
     * Create an instance of {@link Jobs.Job.Params.Param }
     * 
     */
    public Jobs.Job.Params.Param createJobsJobParamsParam() {
        return new Jobs.Job.Params.Param();
    }

    /**
     * Create an instance of {@link Jobs.Job }
     * 
     */
    public Jobs.Job createJobsJob() {
        return new Jobs.Job();
    }

}
